name: flutter_media_metadata_ex
description: A Flutter plugin to read metadata of media files.
version: 1.0.0
homepage: https://github.com/alexmercerind/flutter_media_metadata_ex
repository: https://github.com/alexmercerind/flutter_media_metadata_ex
documentation: https://github.com/alexmercerind/flutter_media_metadata_ex/blob/master/README.md

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.alexmercerind.flutter_media_metadata_ex
        pluginClass: FlutterMediaMetadataExPlugin
      windows:
        pluginClass: FlutterMediaMetadataExPlugin
      linux:
        pluginClass: FlutterMediaMetadataExPlugin
      ios:
        pluginClass: FlutterMediaMetadataExPlugin
      macos:
        pluginClass: FlutterMediaMetadataExPlugin
      web:
        pluginClass: MetadataRetriever
        fileName: src/flutter_media_metadata_ex_web.dart
